repository_type: pipeline

nf_core_version: 3.2.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-hmfrnaseq_logo_light.png
    - docs/images/nf-core-hmfrnaseq_logo_light.png
    - docs/images/nf-core-hmfrnaseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/workflows/linting.yml
  modules_config:
    - rseqc/splitbam
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
    - params.rrna_threshold_count
    - params.rrna_threshold_percent
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-hmfrnaseq_logo_light.png
    - docs/images/nf-core-hmfrnaseq_logo_light.png
    - docs/images/nf-core-hmfrnaseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
  nf_test_content: false

template:
  org: nf-core
  name: hmfrnaseq
  description: Internal rnaseq pipeline for HMF
  author: Rayan Hassaine
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: false
